### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by JackZeled0n** [librespeed/speedtest#440]
## Description
Add dark mode to https://librespeed.org/

## Why it should be implemented

- Can potentially reduce eye strain and dry eyes in low-light conditions
- There will be less ‘blue light’ emitted from your devices
- Inclusition: Some experts say dark mode can help people with light sensitivity or visual impairment.

**Comment by adolfintel** [comment]
Hey, sorry for the late reply.
The code for the frontend of the librespeed.org is hosted here: https://codeberg.org/librespeed/librespeed-frontend

Keep in mind that the UI in this repository is meant to be used as an example/template so adding a dark mode here would just make the examples unnecessarily complicated to read.

**Comment by JackZeled0n** [comment]
@adolfintel but we would add new css for styles  and few lines of js for making the switch button.

**Comment by adolfintel** [comment]
If you're so keen on adding dark mode into the main repo (which I've been opposed to for years btw :laughing:) I suggest you use the `@media (prefers-dark-interface)` media query in the CSS instead of adding a button, that way it will follow the user's system preference.

I still think you should do it only on the librespeed.org website though, the examples are already long enoguh.

**Comment by JackZeled0n** [comment]
Ok 😅
Thanks @adolfintel

**Comment by EpicLPer** [comment]
Have there been any updates on this 😅 
I just deployed this as a Docker container and honestly it works great, the only real downside so far is that it basically flashbangs me whenever I open the page 😆

**Comment by dougmaitelli** [comment]
I see Dark Model in the changelog for version 5.4.0, but I still don't see any option in the UI and Dark Mode does not follow system preferences

**Comment by adolfintel** [comment]
@dougmaitelli it should activate automatically (or at least it does for me): https://github.com/librespeed/speedtest/blob/420be5e72f5c1a59ed9c9201b3625e883555982d/index.html#L403

![image](https://github.com/user-attachments/assets/d26dd7f0-f6fc-4ea2-b5d4-c58e5f60d961)

**Comment by dougmaitelli** [comment]
@adolfintel It does not work at all for me, can confirm I have latest version, it shows on console:
![image](https://github.com/user-attachments/assets/333180f6-ca3a-497d-803e-7a1b1af45009)

But it is still using light mode on both Chrome and Arc (system and browser are set to dark theme):
![image](https://github.com/user-attachments/assets/ef968343-4c50-4e4c-9bd4-89c90d7acfe8)

**Comment by c0f** [comment]
I've got the same issue. I'm running 5.4.1 and there is no option to enable dark mode.

I've tried it in Firefox and Chrome and my browser and system are set to dark mode.

**Comment by sstidl** [comment]
![Screenshot_20241027_160536_Chrome](https://github.com/user-attachments/assets/0ea98387-0bef-4979-af77-a1c7847aa478)
![Screenshot_20241027_160518_Chrome](https://github.com/user-attachments/assets/1db9bef5-a0b3-4c4f-9697-7644b568f3f6)

Here hownit looks on my Android Smartphone Chrome.
I can control it by setting darkmode for the whole phone.

**Comment by dougmaitelli** [comment]
Ok, I am confused, I see the original PR added CSS dark mode to the example html files. I have no idea what those example files are, I use the docker image.
I assume these example html files are options people can use when copying the files of librespeed on their webserver manually? What about the docker image then? Any way to switch which html is served from the container? Is this why we can't see a dark mode option? Can someone please explain this?

**Comment by dougmaitelli** [comment]
Well, in my case, it seems my stack was pulling the image from linuxserver/librespeed:5.4 and not ghcr.io/librespeed/speedtest:5.4
Not sure why there is a copy of the image there with same version but without dark mode.
